/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
    return {
        Map: (() => {
            return defineComponent(
                world,
                { player: RecsType.BigInt, token_id: RecsType.BigInt, size: RecsType.Number, environment: RecsType.Number, structure: RecsType.Number, legendary: RecsType.Number, layout1: RecsType.BigInt, layout2: RecsType.BigInt, layout3: RecsType.BigInt, doors1: RecsType.BigInt, doors2: RecsType.BigInt, doors3: RecsType.BigInt, points1: RecsType.BigInt, points2: RecsType.BigInt, points3: RecsType.BigInt, affinity: RecsType.BigInt, dungeon_name1: RecsType.BigInt, dungeon_name2: RecsType.BigInt, dungeon_name3: RecsType.BigInt, dungeon_name4: RecsType.BigInt, dungeon_name5: RecsType.BigInt, owner: RecsType.String },
                {
                    metadata: {
                        name: "Map",
                        types: ["u8", "u8", "u8", "u8", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252", "felt252"],
                    },
                }
            );
        })(),
        Moves: (() => {
            return defineComponent(
                world,
                {
                    player: RecsType.BigInt,
                    remaining: RecsType.Number,
                    last_direction: RecsType.Number,
                },
                {
                    metadata: {
                        name: "Moves",
                        types: ["contractaddress", "u8", "enum"],
                        customTypes: ["Direction"],
                    },
                }
            );
        })(),
        Position: (() => {
            return defineComponent(
                world,
                {
                    player: RecsType.BigInt,
                    vec: { x: RecsType.Number, y: RecsType.Number },
                },
                {
                    metadata: {
                        name: "Position",
                        types: ["contractaddress", "u32", "u32"],
                        customTypes: ["Vec2"],
                    },
                }
            );
        })(),
    };
}
